### ISSUE TITLE
/usr/include/flann/util/serialization.h:34:14: error: ‘class std::unordered_map<unsigned int, std::vector<unsigned int> >’ has no member named ‘serialize’

### ISSUE THREAD

**Issue by JokerJohn** [APRIL-ZJU/clins#12]
编译clins_offline_node节点的时候出现这个报错，flann与opencv冲突，请问如何解决？

**Comment by zyqww** [comment]
Hello, I also encountered the same problem, did you solve it?

**Comment by Peterwangwei** [comment]
Me too, I spent one day trying to solve the problem, but I failed. Did anyone succeed?
