### ISSUE TITLE
lidar 残差和 imu 残差权重的选取

### ISSUE THREAD

**Issue by zeng-xiangwei** [APRIL-ZJU/clins#3]
大佬好，我最近打算按照你们在 IROS 上的论文复现大佬的工作，但是我目前有两个问题，
1、lidar 残差和 imu 残差权重如何选取？imu 残差是直接用测量噪声的方差的逆（1/σ^2）作为权重吗？如果是的话，需要借助一些标定手段，标定出测量噪声吗？lidar 残差是类似 loam，按照点面（点线）距离来取权重吗？
2、重力方向的 roll 和 pitch，是在整个系统初始化的时候计算出来，然后固定住吗？

期待大佬回复，祝大佬论文早日发表！

**Comment by icameling** [comment]
你好，

理论上而言，残差权重需要依据测量噪声给定，但是考虑到以下两个因素，我们基于经验值设置残差权重；

用IMU噪声标定结果与实际工作时的情况不一致；比如激光和IMU刚性连接，旋转式激光会使装置震动，导致IMU测量噪声增大；
激光测量精度与测量距离、测量角度有关；
是的。

非常感谢你关注我们的工作。

**Comment by icameling** [comment]
你好，

1. 理论上而言，残差权重需要依据测量噪声给定，但是考虑到以下两个因素，我们基于经验值设置残差权重；

    - 用IMU噪声标定结果与实际工作时的情况不一致；比如激光和IMU刚性连接，旋转式激光会使装置震动，导致IMU测量噪声增大；
    - 激光测量精度与测量距离、测量角度有关；
2. 是的。

非常感谢你关注我们的工作。
